const data = {
  categories: [
    'Books',
    'Appliances',
    'Apps & Games',
    'Arts, Crafts & Sewing',
    'Automated Parts & Accesories',
    'Baby',
    'Beauty & Personal Care',
    'CDs & Vinyl',
    'Cell Phones & Accessories',
    'Clothing, Shoes & Jewelery',
    'Under $10',
    'Collectibles & Fine Art',
    'Computers',
    'Courses',
    'Digital Educational Resources',
    'Digital Music',
    'Electronics',
    'Garden & Outdoor',
    'Grocery & Gourmet Food',
    'Handmade',
    'Health, Household & Baby Care',
    'Home & Business Services',
    'Home & Kitchen',
    'Industrial & Scientific',
    'Luggage & Travel Gear',
    'Musical Insturments',
    'Office Products',
    'Pet Supplies',
    'Premium Beauty',
    'Smart Home',
    'Software',
    'Sports & Outdoors',
    'Tools & Home Improvement',
    'Toys & Games',
    'Vehicles',
    'Video Games',
  ],
  businesses: [],
};

module.exports = {
  data,
};
