const data = {
  categories: [
    "Books",
    "Appliances",
    "Apps & Games",
    "Arts, Crafts & Sewing",
    "Automated Parts & Accesories",
    "Baby",
    "Beauty & Personal Care",
    "CDs & Vinyl",
    "Cell Phones & Accessories",
    "Clothing, Shoes & Jewelery",
    "Under $10",
    "Collectibles & Fine Art",
    "Computers",
    "Courses",
    "Digital Educational Resources",
    "Digital Music",
    "Electronics",
    "Garden & Outdoor",
    "Grocery & Gourmet Food",
    "Handmade",
    "Health, Household & Baby Care",
    "Home & Business Services",
    "Home & Kitchen",
    "Industrial & Scientific",
    "Luggage & Travel Gear",
    "Musical Insturments",
    "Office Products",
    "Pet Supplies",
    "Premium Beauty",
    "Smart Home",
    "Software",
    "Sports & Outdoors",
    "Tools & Home Improvement",
    "Toys & Games",
    "Vehicles",
    "Video Games",
  ],
  businesses: [
    [
      "East Road Beverages",
      "Alchohol",
      "http://www.eastroadbeverages.com/",
      "Maryland-based East Road Beverages —which, like many distilleries, has temporarily closed to the public—is manufacturing ethanol-based hand sanitizer to distribute to local hospitals, doctors’ offices, nursing homes, etc. We’re even going to distribute to local supermarket workers and will set aside some for the general public. We are excited about making a difference by combating the growth of the virus and, potentially, saving lives.",
      "Official Black Wall Street",
      "Health & Household",
    ],
    [
      "The Advocates Tees",
      "Men's Fashion",
      "www.theadvocatestee.com",
      "The Advocates is a social awareness brand that provides a wearable platform for your truth to be heard.",
      "Official Black Wall Street",
      "Clothing, Shoes & Jewelery",
      "Social justice T-shirts ",
    ],
    [
      "Brilliantly Designed LLC",
      "Men's Fashion",
      "http://www.brilliantlydesignedllc.com/",
      "Brilliantly Designed LLC makes custom products for you. Check out the website or send a message about what we can make for you.",
      "Official Black Wall Street",
      "Clothing, Shoes & Jewelery",
      "Tees celebrating the Black experience",
    ],
    [
      "Body Varsity LLC",
      "Beauty",
      "https://bodyvarsity.com/home",
      "ML Delicate Beauty offers the best natural anti-aging face and body care products: Vitamin C Serum, Stretch Mark Removal Cream & Retinol Moisturizer. Anti-Aging Skincare Products for All Skin Types.",
      "Official Black Wall Street",
    ],
    [
      "Vidaluxlook",
      "Food & Beverage",
      "http://www.vidaluxlook.com/",
      "Vidaluxlook is a woman-owned black business that was created as a platform for a lifestyle of holistic therapy through their lux infused cooking oils. With eight tantalizing flavors to choose from, you can’t go wrong. Vidaluxlook is not only gourmet organic oils, but they are infused with herbs and slices such as lavender buds, Rosemary, mint, and violet sea salt to name a few. These seasonings blend well on your palate no matter what your dietary needs.",
      "Official Black Wall Street",
    ],
    [
      "ML Delicate Beauty",
      "Beauty",
      "https://mldelicatebeauty.com/",
      "ML Delicate Beauty offers the best natural anti-aging face and body care products: Vitamin C Serum, Stretch Mark Removal Cream & Retinol Moisturizer. Anti-Aging Skincare Products for All Skin Types",
      "Official Black Wall Street",
    ],
    [
      "Blk-ed",
      "Accessories",
      "http://www.blk-ed.com/",
      "Blk-ed is a new and ground breaking company based іn Canada/USA. Our mіѕѕіоn is to develop products that truly reflect the beauty, pride and strength of our people. One of our main gоаls аt Blk-еd is tо provide beautifully designed products with images that resonate with our communities at first sight. Some of the products include school bags for children leather wallets for him and her, tote bags and much more.",
      "Official Black Wall Street",
      "Clothing, Shoes & Jewelery",
      "Afrocentric bags and accessories",
    ],
    [
      "I Am Unique",
      "Accessories",
      "https://iamunique.me/",
      "Handmade jewelry and accessories that are one of a kind. Beautiful colorful, statement pieces that can bring out your personality. Custom orders accepted.",
      "jewelry mystery box",
      "Clothing, Shoes & Jewelery",
      "Handmade jewelry and accessories",
    ],
    [
      "Hey Silly Milly",
      "Children's Books",
      "https://www.heysillymilly.com/",
      "Milan Hoy is a new Indie author seeking to inspire others to pursue their goal by publishing her first book. At just eleven years old, Milan’s resume already includes modeling, acting, and the recent title of author. Milan uses the protagonist of her book to make statements on social media like “Make your mark!” or “Nurture your dreams!” She hopes to connect with her audience through creating relatable content with positive messages.",
      "Official Black Wall Street",
    ],
    [
      "Drippy Self Love",
      "Beauty",
      "https://drippyselflove.bigcartel.com/",
      "Handcrafted natural skin products. Hand picked each herb, spice & scent. Top notch skin ingredients. 100% organic, vegan, cruelty-free solutions 4 ur skin.",
      "Official Black Wall Street",
    ],
    [
      "Ebonyx",
      "Everything",
      "https://ebonyx.co.uk/",
      "Searching for a marketplace to buy African and Caribbean inspired items and finding none, founders Ashley and Lucan decided to create their own – Ebonyx – ‘The marketplace for anything afrocentric’.Partnering with individual brands, you can shop hundreds of sought after items including African inspired fashion, products for textured hair types, Caribbean inspired jewellery, Ankara printed home décor, and much more.You can also sign up with a free account and start earning rewards. Simply refer-a-friend or spend, and begin to redeem rewards including gift cards, electronics, international flights, and more.",
      "Official Black Wall Street",
    ],
    [
      "Irie Herbz Apothecary",
      "Beauty",
      "http://irieherbzapothecary.com/",
      "Irie Herbz Apothecary is an online beauty boutique that features luxury cosmetic products and herbal supplements. Visit our website to learn more!",
      "Official Black Wall Street",
    ],
    [
      "Rema Collections African Shop",
      "Apparel & Accessories",
      "https://remacollections.com/",
      "African Fashion & Accessories store in Bay Area, CA. Come see our rich supply of clothes, shoes, handbags, jewelry, art, healthy & beauty products and more authentic African goods at Rema Collections. Custom made apparel tailored to fit you on your special day or every day clothing. Supply your health cabinet with African Soaps, Lotions, Perfumes. Decorate your home with African Art, Masks, Sculptures & more.",
      "Official Black Wall Street",
      "Clothing, Shoes & Jewelery",
      "African fashion and accessories",
    ],
    [
      "Clear Essence Skin Care",
      "Apparel & Accessories",
      "https://www.clearessence.com/",
      "African Fashion & Accessories store in Bay Area, CA. Come see our rich supply of clothes, shoes, handbags, jewelry, art, healthy & beauty products and more authentic African goods at Rema Collections. Custom made apparel tailored to fit you on your special day or every day clothing. Supply your health cabinet with African Soaps, Lotions, Perfumes. Decorate your home with African Art, Masks, Sculptures & more.",
      "Official Black Wall Street",
      "Beauty & Personal Care",
      "Natural skin care",
    ],
    [
      "Green Olive Soaps",
      "Beauty & Personal Care",
      "https://www.greenolivesoaps.com/",
      "Green Olive Soaps is based in Troy, MI and specialize in Vegan & Organic Whipped Shea Butter, Spa Salt Bars, Bubble Bars, Bath Salts, Sugar Scrubs, & Soaps. We are known for our Soap Cupcakes and have recently joined PETA's cruelty-free list. Green Olive Soaps create soaps for eczema and sensitive skin. Our prices range from $5 – $15 and our Gift Boxes with ribbon are only $3. We aim to provide vegan and organic bath products at affordable prices.",
      "Official Black Wall Street",
      "Beauty & Personal Care",
      "Handcrafted soaps and bath products",
    ],
    [
      "Queen Virgin Remy",
      "Beauty & Personal Care",
      "https://www.queenvirginremy.com/",
      "Queen Virgin Remy, the largest distributor of exotic virgin extensions in the U.S., is black owned, black operated and black proud.",
      "Official Black Wall Street",
      "Beauty & Personal Care",
      "Virgin hair extensions",
    ],
    [
      "Loving Me Books",
      "Books",
      "https://www.lovingmebooks.com/",
      "Detroit, Michigan native Angela Nesbitt, founded Loving Me Books to promote self-love and unify children of all races . While working in schools as an Behavioral Therapist, Angela witnessed the lack of diverse children books in classrooms and libraries. Angela is dedicated to implementing children's books for underrepresented minority children. Loving Me Books specialty children’s bookstore provides services to schools, daycares, book fairs, and on our website. Screen reader support enabled.",
      "Official Black Wall Street",
      "Books",
      "Because loving me is loving you.",
    ],
    [
      "Kizzy's Books & More",
      "Books",
      "https://www.kizzysbooksandmore.com/",
      "Kizzy's Books & More is an independent bookstore committed to embracing the African-American culture and the joy of reading. We aim to provide a place for lovers of African-American literature and other creative expressions with a welcoming ambiance and customer service. The company additionally seeks to provide a comfortable atmosphere for its customers that promote browsing, relaxation, and an enjoyable environment to spend extended time in.",
      "Official Black Wall Street",
      "Books",
      "Online bookstore",
    ],
    [
      "Black Classic Press",
      "Books",
      "https://www.queenvirginremy.com/",
      "Founded in 1978, Black Classic Press is devoted to publishing obscure and significant works by and about people of African descent. We specialize in republishing works that are out of print and quite often out of memory. We began publishing because we wanted to extend the memory of what we believe are important books that have helped in meaningful ways to shape the Black diasporic experience and our understanding of the world",
      "Official Black Wall Street",
      "Books",
      "Online bookstore",
    ],
    [
      "The Key Bookstore",
      "Books",
      "https://keybookstore.com/shop/",
      "The Key Bookstore is a fully interactive bookstore experience. The Key engages readers through curation, activities, subscriptions, events, events, and community engagement. The focus is to lead readers on a path to Self Mastery and the cultivation of connection on and offline with respect to the mission, “Divine liberation one page at a time”. This store is curated on for the pillars Afrocentricity, Spirituality Environmentalism, and Entrepreneurship.",
      "Official Black Wall Street",
      "Books",
      "Online bookstore",
    ],
    [
      "The Literacy Shop",
      "Books",
      "https://www.theliteracyshop.com/shop",
      "The Literacy Shop was birthed from several conversations between its owner, Leslie Crawford, and elementary school kids. When Leslie was a substitute teacher in Baltimore County, she would have several conversations with her students. During one conversation, Leslie asked a group, why didn't they like reading books? Their response was there are no books that I can relate to. From this one conversation, Leslie's love of writing and her passion for literacy, The Literacy Shop, was birthed.",
      "Official Black Wall Street",
      "Books",
      "Where we are making reading dope.",
    ],
  ],
};

module.exports = {
  data,
};
