const data = {
  categories: [
    "Books",
    "Appliances",
    "Apps & Games",
    "Arts, Crafts & Sewing",
    "Automated Parts & Accesories",
    "Baby",
    "Beauty & Personal Care",
    "CDs & Vinyl",
    "Cell Phones & Accessories",
    "Clothing, Shoes & Jewelery",
    "Under $10",
    "Collectibles & Fine Art",
    "Computers",
    "Courses",
    "Digital Educational Resources",
    "Digital Music",
    "Electronics",
    "Garden & Outdoor",
    "Grocery & Gourmet Food",
    "Handmade",
    "Health, Household & Baby Care",
    "Home & Business Services",
    "Home & Kitchen",
    "Industrial & Scientific",
    "Luggage & Travel Gear",
    "Musical Insturments",
    "Office Products",
    "Pet Supplies",
    "Premium Beauty",
    "Smart Home",
    "Software",
    "Sports & Outdoors",
    "Tools & Home Improvement",
    "Toys & Games",
    "Vehicles",
    "Video Games",
  ],
  businesses: [
    [
      "East Road Beverages",
      "Alchohol",
      "http://www.eastroadbeverages.com/",
      "Maryland-based East Road Beverages —which, like many distilleries, has temporarily closed to the public—is manufacturing ethanol-based hand sanitizer to distribute to local hospitals, doctors’ offices, nursing homes, etc. We’re even going to distribute to local supermarket workers and will set aside some for the general public. We are excited about making a difference by combating the growth of the virus and, potentially, saving lives.",
      "Official Black Wall Street",
    ],
    [
      "The Advocates Tees",
      "Apparel",
      "www.theadvocatestee.com",
      "The Advocates is a social awareness brand that provides a wearable platform for your truth to be heard.",
      "Official Black Wall Street",
    ],
    [
      "Brilliantly Designed LLC",
      "Apparel & Accessories",
      "http://www.brilliantlydesignedllc.com/",
      "Brilliantly Designed LLC makes custom products for you. Check out the website or send a message about what we can make for you.",
      "Official Black Wall Street",
    ],
    [
      "Body Varsity LLC",
      "Beauty",
      "https://bodyvarsity.com/home",
      "ML Delicate Beauty offers the best natural anti-aging face and body care products: Vitamin C Serum, Stretch Mark Removal Cream & Retinol Moisturizer. Anti-Aging Skincare Products for All Skin Types.",
      "Official Black Wall Street",
    ],
    [
      "Vidaluxlook",
      "Food & Beverage",
      "http://www.vidaluxlook.com/",
      "Vidaluxlook is a woman-owned black business that was created as a platform for a lifestyle of holistic therapy through their lux infused cooking oils. With eight tantalizing flavors to choose from, you can’t go wrong. Vidaluxlook is not only gourmet organic oils, but they are infused with herbs and slices such as lavender buds, Rosemary, mint, and violet sea salt to name a few. These seasonings blend well on your palate no matter what your dietary needs.",
      "Official Black Wall Street",
    ],
    [
      "ML Delicate Beauty",
      "Beauty",
      "https://mldelicatebeauty.com/",
      "ML Delicate Beauty offers the best natural anti-aging face and body care products: Vitamin C Serum, Stretch Mark Removal Cream & Retinol Moisturizer. Anti-Aging Skincare Products for All Skin Types",
      "Official Black Wall Street",
    ],
    [
      "Blk-ed",
      "Accessories",
      "http://www.blk-ed.com/",
      "Blk-ed is a new and ground breaking company based іn Canada/USA. Our mіѕѕіоn is to develop products that truly reflect the beauty, pride and strength of our people. One of our main gоаls аt Blk-еd is tо provide beautifully designed products with images that resonate with our communities at first sight. Some of the products include school bags for children leather wallets for him and her, tote bags and much more.",
      "Official Black Wall Street",
    ],
    [
      "Hey Silly Milly",
      "Children's Books",
      "https://www.heysillymilly.com/",
      "Milan Hoy is a new Indie author seeking to inspire others to pursue their goal by publishing her first book. At just eleven years old, Milan’s resume already includes modeling, acting, and the recent title of author. Milan uses the protagonist of her book to make statements on social media like “Make your mark!” or “Nurture your dreams!” She hopes to connect with her audience through creating relatable content with positive messages.",
      "Official Black Wall Street",
    ],
    [
      "Drippy Self Love",
      "Beauty",
      "https://drippyselflove.bigcartel.com/",
      "Handcrafted natural skin products. Hand picked each herb, spice & scent. Top notch skin ingredients. 100% organic, vegan, cruelty-free solutions 4 ur skin.",
      "Official Black Wall Street",
    ],
    [
      "Ebonyx",
      "Everything",
      "https://ebonyx.co.uk/",
      "Searching for a marketplace to buy African and Caribbean inspired items and finding none, founders Ashley and Lucan decided to create their own – Ebonyx – ‘The marketplace for anything afrocentric’.Partnering with individual brands, you can shop hundreds of sought after items including African inspired fashion, products for textured hair types, Caribbean inspired jewellery, Ankara printed home décor, and much more.You can also sign up with a free account and start earning rewards. Simply refer-a-friend or spend, and begin to redeem rewards including gift cards, electronics, international flights, and more.",
      "Official Black Wall Street",
    ],
  ],
};

module.exports = {
  data,
};
